################################主配置文件，公共部分配置放这里################################

#激活配置文件
spring.profiles.active: dev

#日志配置
logging.config: 'classpath:config/logback.xml'

#session超时时间（分钟）
server:
  session-timeout: 120

#tomcat优化
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 3000
    min-spare-threads: 500
#自定义的tomcat配置
custom:
  tomcat:
    max-connections: 10000
    connection-timeout: 60000


#jackson配置
spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'Asia/Chongqing'
  mvc:
    date-format: 'yyyy-MM-dd HH:mm:ss'


#文件上传配置
spring:
  http:
    multipart:
      enabled: true
      file-size-threshold: 3Mb
      max-file-size: 50Mb
      max-request-size: 10Mb

#支持多彩日志输出
#  output:
#      ansi:
#        enabled: detect

# BANNER
banner:
  charset: UTF-8
  location: 'classpath:config/banner.txt'